### PR TITLE
Fruit clean up

### PR DESCRIPTION
**Pull request by chwarr**
This change is [Reviewable](https://reviewable.io/reviews/chwarr/playground/6)

### CODE REVIEW

**Comment by tstein** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[fruit.txt, line 5 at r2](https://reviewable.io:443/reviews/chwarr/playground/6#-KrYKuPjPU-QHSYRWLIh:-KrYKuPklupSP7MVfHNz:b5j9378) ([raw file](https://github.com/chwarr/playground/blob/10165142387837d0b1c833ad35b04eccec77416c/fruit.txt#L5)):*
> ```
> blackberry
> blackcurrant
> crookneck squash
> ```

also not a fruit

---

*[fruit.txt, line 8 at r2](https://reviewable.io:443/reviews/chwarr/playground/6#-KrYKk-mZnery8dRC3Au:-KrYKk-mZnery8dRC3Av:b-f8o8d9) ([raw file](https://github.com/chwarr/playground/blob/10165142387837d0b1c833ad35b04eccec77416c/fruit.txt#L8)):*
> ```
> guava
> pear
> raspberry
> ```

raspberry is good though

---

*[fruit.txt, line 9 at r2](https://reviewable.io:443/reviews/chwarr/playground/6#-KrYKV0MFC6wucIxaxdT:-KrYKV0NMMcRn9MnJ0YT:b-y4nd2x) ([raw file](https://github.com/chwarr/playground/blob/de75592b5070985995ced0e881d9af4251247c74/fruit.txt#L9)):*
> ```
> peach
> pear
> pineapple
> ```

why would you get rid of *pineapple*

---

*[fruit.txt, line 11 at r2](https://reviewable.io:443/reviews/chwarr/playground/6#-KrYKnObHL6kNViVou7g:-KrYKnObHL6kNViVou7h:b-8ro4rb) ([raw file](https://github.com/chwarr/playground/blob/10165142387837d0b1c833ad35b04eccec77416c/fruit.txt#L11)):*
> ```
> strawberry
> tomato
> zucchini
> ```

this isn't a fruit

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chwarr/playground/6)*

**Comment by chwarr** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[fruit.txt, line 5 at r2](https://reviewable.io:443/reviews/chwarr/playground/6#-KrYKuPjPU-QHSYRWLIh:-KrYLZ4zShsTnCOSET-G:br5ah4g) ([raw file](https://github.com/chwarr/playground/blob/10165142387837d0b1c833ad35b04eccec77416c/fruit.txt#L5)):*
<details><summary><i>Previously, tstein (Ted Stein) wrote…</i></summary><blockquote>

also not a fruit
</blockquote></details>

This file is supposed to be biological fruit, not culinary fruit. See [_Nix v. Hedden_](https://en.wikipedia.org/wiki/Nix_v._Hedden).

---

*[fruit.txt, line 9 at r2](https://reviewable.io:443/reviews/chwarr/playground/6#-KrYKV0MFC6wucIxaxdT:-KrYLvP6UjhWsxRERA_I:bhfelrx) ([raw file](https://github.com/chwarr/playground/blob/de75592b5070985995ced0e881d9af4251247c74/fruit.txt#L9)):*
<details><summary><i>Previously, tstein (Ted Stein) wrote…</i></summary><blockquote>

why would you get rid of *pineapple*
</blockquote></details>

We're refactoring all the 'p' fruit out. There are just too many of them.

---

*[fruit.txt, line 11 at r2](https://reviewable.io:443/reviews/chwarr/playground/6#-KrYKnObHL6kNViVou7g:-KrYM7mSaOml6QYKPhor:b-q64pkt) ([raw file](https://github.com/chwarr/playground/blob/10165142387837d0b1c833ad35b04eccec77416c/fruit.txt#L11)):*
<details><summary><i>Previously, tstein (Ted Stein) wrote…</i></summary><blockquote>

this isn't a fruit
</blockquote></details>

See above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chwarr/playground/6)*

**Comment by tstein** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[culinary-vegetables.txt, line 2 at r5](https://reviewable.io:443/reviews/chwarr/playground/6#-KrYODr8Pv2TrjefaUDN:-KrYODr8Pv2TrjefaUDO:b3zjuo3) ([raw file](https://github.com/chwarr/playground/blob/e52946f9ea97518514b59ec11246a22c48813d9d/culinary-vegetables.txt#L2)):*
> ```
> crookneck squash
> tomato
> ```

this is weird but I'll deal

---

*[fruit.txt, line 5 at r2](https://reviewable.io:443/reviews/chwarr/playground/6#-KrYKuPjPU-QHSYRWLIh:-KrYNiupk1nzLMqhO6bp:b-1a6446) ([raw file](https://github.com/chwarr/playground/blob/10165142387837d0b1c833ad35b04eccec77416c/fruit.txt#L5)):*
<details><summary><i>Previously, chwarr (Christopher Warrington) wrote…</i></summary><blockquote>

This file is supposed to be biological fruit, not culinary fruit. See [_Nix v. Hedden_](https://en.wikipedia.org/wiki/Nix_v._Hedden).
</blockquote></details>

ok but squash still isn't fruit

---

*[fruit.txt, line 8 at r2](https://reviewable.io:443/reviews/chwarr/playground/6#-KrYKk-mZnery8dRC3Au:-KrYO4UUAi-7k7EoQMeh:b-1l1zak) ([raw file](https://github.com/chwarr/playground/blob/10165142387837d0b1c833ad35b04eccec77416c/fruit.txt#L8)):*
<details><summary><i>Previously, tstein (Ted Stein) wrote…</i></summary><blockquote>

raspberry is good though
</blockquote></details>

well ok then

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chwarr/playground/6)*

**Comment by tstein** [comment]
:lgtm: but the dictionary is sad

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chwarr/playground/6#-:-KrYOhtc3B3rN-s9gZiI:b-spicdv)*

**Comment by tstein** [comment]
Reviewed 2 of 2 files at r8.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[fruit.txt, line 1 at r8](https://reviewable.io:443/reviews/chwarr/playground/6#-KrYPvWC4XM_RxVwh620:-KrYPvWC4XM_RxVwh621:b-km1xxq) ([raw file](https://github.com/chwarr/playground/blob/a890afd6ffe33444414eda03f4bfa177cc61adf8/fruit.txt#L1)):*
> ```
> APPLE
> ```

WHY ARE WE SHOUTING

---

*[fruit.txt, line 9 at r8](https://reviewable.io:443/reviews/chwarr/playground/6#-KrYPsp8hY9qs2xx_Zh5:-KrYPsp9Lc5BuDnFG4Sr:b-er4kdn) ([raw file](https://github.com/chwarr/playground/blob/a890afd6ffe33444414eda03f4bfa177cc61adf8/fruit.txt#L9)):*
> ```
> RASPBERRY
> STRAWBERRY
> u
> ```

strong work

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chwarr/playground/6)*

**Comment by chwarr** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[fruit.txt, line 1 at r8](https://reviewable.io:443/reviews/chwarr/playground/6#-KrYPvWC4XM_RxVwh620:-KrYQJHsD010UA2Vx994:bddl9qj) ([raw file](https://github.com/chwarr/playground/blob/a890afd6ffe33444414eda03f4bfa177cc61adf8/fruit.txt#L1)):*
<details><summary><i>Previously, tstein (Ted Stein) wrote…</i></summary><blockquote>

WHY ARE WE SHOUTING
</blockquote></details>

I DON'T KNOW. YOU STARTED IT?

---

*[fruit.txt, line 9 at r8](https://reviewable.io:443/reviews/chwarr/playground/6#-KrYPsp8hY9qs2xx_Zh5:-KrYQlDJiDtRjvpV68Gl:b-896fix) ([raw file](https://github.com/chwarr/playground/blob/a890afd6ffe33444414eda03f4bfa177cc61adf8/fruit.txt#L9)):*
<details><summary><i>Previously, tstein (Ted Stein) wrote…</i></summary><blockquote>

strong work
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chwarr/playground/6)*

**Comment by tstein** [comment]
Reviewed 1 of 1 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chwarr/playground/6)*

**Pull request merged**
